1.1 EJERCICIO MODULO 3 NUMPY

# Ejercicios

1.  Genera un *array* bidimensional de 4 x 3 con valores aleatorios enteros entre el 34 y el 98. Una vez creado cada array comprueba las dimensiones y los tipos de datos que tenemos en el array. 

2. Crea dos *arrays* (unidimensional, bidimensional) usando el método `np.array()`. 

    Las listas para crear los *arrays* son las siguientes

    ```python
    lista1 = [34,56,71,98, 10]
    lista2 = [[23,45,89, 56], [12,43,82,44]]
    ```

    **Bonus** Haz una pequeña descripción de cada *array* usando los métodos de exploración de *arrays* que hemos aprendido.


In [5]:
# importando librerias
import numpy as np

In [6]:
""" 1.  Genera un array bidimensional de 4 x 3 con valores aleatorios enteros entre el 34 y el 98. Una vez creado cada array comprueba
las dimensiones y los tipos de datos que tenemos en el array."""

# Generar un array bidimensional de 4x3 con valores aleatorios entre 34 y 98
array_aleatorio = np.random.randint(34, 99, size=(4, 3))

# Comprobar las dimensiones del array
dimensiones = array_aleatorio.shape

# Comprobar el tipo de dato del array
tipo_dato = array_aleatorio.dtype

# Imprimir el array generado, dimensiones y tipo de dato
print("Array generado:")
print(array_aleatorio)
print("Dimensiones del array:", dimensiones)
print("Tipo de dato del array:", tipo_dato)

Array generado:
[[94 83 39]
 [77 80 49]
 [96 92 50]
 [66 58 93]]
Dimensiones del array: (4, 3)
Tipo de dato del array: int32


In [10]:
"""
2.Crea dos arrays (unidimensional, bidimensional) usando el método `np.array()`. 

    Las listas para crear los *arrays* son las siguientes

    ```python
    lista1 = [34,56,71,98, 10]
    lista2 = [[23,45,89, 56], [12,43,82,44]]
    ```

    **Bonus** Haz una pequeña descripción de cada array usando los métodos de exploración de arrays que hemos aprendido.

"""

# Listas para crear los arrays
lista1 = [34, 56, 71, 98, 10]
lista2 = [[23, 45, 89, 56], [12, 43, 82, 44]]

# Crear el array unidimensional
array_unidimensional = np.array(lista1)

# Crear el array bidimensional
array_bidimensional = np.array(lista2)

print("descripcion del array unidimensional")
print("-----------------------------------------")
print(f"El array unidimensional es: \n  {array_unidimensional}")
print(f"La forma del array unidimensional es: {array_unidimensional.shape}")
print(f"El número de dimensiones del array unidimensional es: {array_unidimensional.ndim}")
print(f"El número de elementos del array unidimensional es: {array_unidimensional.size}")
print(f"El tipo de dato que tenemos en el array unidimensional es: {array_unidimensional.dtype}\n")
print()
print("-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-")
print()
print("descripcion del array bidimensional")
print("-----------------------------------------")
print(f"El array bidimensional es: \n  {array_bidimensional}")
print(f"La forma del array bidimensional es: {array_bidimensional.shape}")
print(f"El número de dimensiones del array bidimensional es: {array_bidimensional.ndim}")
print(f"El número de elementos del array bidimensional es: {array_bidimensional.size}")
print(f"El tipo de dato que tenemos en el array bidimensional es: {array_bidimensional.dtype}\n")

descripcion del array unidimensional
-----------------------------------------
El array unidimensional es: 
  [34 56 71 98 10]
La forma del array unidimensional es: (5,)
El número de dimensiones del array unidimensional es: 1
El número de elementos del array unidimensional es: 5
El tipo de dato que tenemos en el array unidimensional es: int32


-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-

descripcion del array bidimensional
-----------------------------------------
El array bidimensional es: 
  [[23 45 89 56]
 [12 43 82 44]]
La forma del array bidimensional es: (2, 4)
El número de dimensiones del array bidimensional es: 2
El número de elementos del array bidimensional es: 8
El tipo de dato que tenemos en el array bidimensional es: int32

