1.2 EJERCICIO MODULO 3 INDEXACION

# Ejercicios


1. Crea un *array* unidimensional con 50 elementos con el método que prefieras y extrae: 

    - El primer elemento.


    - Lo elementos que están en posición impar.


    - Los cuatro primeros elementos.


    - Los últimos tres elementos.


    - Los elementos entre el 4 y el 8 (incluido). 

2. Crea un *array* de dos dimensiones de 4 x 5 con el método que prefieras y extrae:

    - La primera fila y todas las columnas.


    - Todas las filas pares.


    - La primera columna y todas las filas.


In [1]:
# IMPORTANDO LIBRERIAS
import numpy as np

In [2]:
"""
1. Crea un array unidimensional con 50 elementos con el método que prefieras y extrae: 

    - El primer elemento.


    - Lo elementos que están en posición impar.


    - Los cuatro primeros elementos.


    - Los últimos tres elementos.


    - Los elementos entre el 4 y el 8 (incluido). 

"""

# Crear un array unidimensional con 50 elementos
array_50 = np.arange(1, 51)

# Extraer el primer elemento
primer_elemento = array_50[0]

# Extraer los elementos en posiciones impares
elementos_impares = array_50[1::2]

# Extraer los cuatro primeros elementos
primeros_cuatro = array_50[:4]

# Extraer los últimos tres elementos
ultimos_tres = array_50[-3:]

# Extraer los elementos entre el 4 y el 8 (incluidos)
entre_4_y_8 = array_50[4:9]

# Imprimir los resultados
print("Primer elemento:", primer_elemento)
print("Elementos en posiciones impares:", elementos_impares)
print("Cuatro primeros elementos:", primeros_cuatro)
print("Últimos tres elementos:", ultimos_tres)
print("Elementos entre el 4 y el 8 (incluidos):", entre_4_y_8)

Primer elemento: 1
Elementos en posiciones impares: [ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48
 50]
Cuatro primeros elementos: [1 2 3 4]
Últimos tres elementos: [48 49 50]
Elementos entre el 4 y el 8 (incluidos): [5 6 7 8 9]


In [3]:
"""
    2. Crea un array de dos dimensiones de 4 x 5 con el método que prefieras y extrae:

    - La primera fila y todas las columnas.


    - Todas las filas pares.


    - La primera columna y todas las filas.
"""

# Crear un array bidimensional de 4x5 usando el metodo random.randint()
array_2d = np.random.randint(0, 50, (4,5))

# Extraer la primera fila y todas las columnas
primera_fila_todas_columnas = array_2d[0, :]

# Extraer todas las filas pares
todas_filas_pares = array_2d[::2, :]

# Extraer la primera columna y todas las filas
primera_columna_todas_filas = array_2d[:, 0]

# Imprimir los resultados
print("mi array 2D es:",array_2d)

print("\nPrimera fila y todas las columnas:",primera_fila_todas_columnas)

print("\nTodas las filas pares:", todas_filas_pares)

print("\nPrimera columna y todas las filas:",primera_columna_todas_filas)


mi array 2D es: [[ 5 47 31 48 39]
 [ 3 27 33 34 11]
 [24 18 46 19 29]
 [26 33 45 29  4]]

Primera fila y todas las columnas: [ 5 47 31 48 39]

Todas las filas pares: [[ 5 47 31 48 39]
 [24 18 46 19 29]]

Primera columna y todas las filas: [ 5  3 24 26]
