# Ejercicios


1. Crea un *array* bidimensional con 20 elementos aleatrorios entre 0 y 50 con el método que prefieras y: 

    - Crea una mascara o filtro donde los valores mayores a 30 y menores a 10 se reemplace por "objetivo" y el resto por "no es mi objetivo".


    - Los valores de mi array bidimensional multiplicalos por el escalar 10.


2. Crea un nuevo *array* de dos dimensiones con la misma forma que el anterior y con el método que prefieras y realiz lo siguiente:

    - Suma el primer array con el segundo.


    - Aplicar la potencia para el primer array elevado al segundo.

In [1]:
# treamos las librerias!
import numpy as np

In [7]:
"""
1. Crea un *array* bidimensional con 20 elementos aleatrorios entre 0 y 50 con el método que prefieras y: 

    - Crea una mascara o filtro donde los valores mayores a 30 y menores a 10 se reemplace por "objetivo" y el resto por "no es mi objetivo".


    - Los valores de mi array bidimensional multiplicalos por el escalar 10.
"""

# creando mi array de 20 elementos aleatorios entre 0 y 50
array = np.random.randint(0, 51, size=(4, 5))
print("mi array")
print(array)

# creando la mascara
mascara = np.where((array > 30) | (array < 10), "objetivo", "no es mi objetivo")
print("\nMáscara:")
print(mascara)

# Multiplicar el array original por el escalar 10
array_mult = array * 10
print("\nArray multiplicado por 10:")
print(array_mult)

mi array
[[ 4 46  9  2 20]
 [12 25 10  4 43]
 [14 38 21 44 44]
 [ 3 46 33  6 25]]

Máscara:
[['objetivo' 'objetivo' 'objetivo' 'objetivo' 'no es mi objetivo']
 ['no es mi objetivo' 'no es mi objetivo' 'no es mi objetivo' 'objetivo'
  'objetivo']
 ['no es mi objetivo' 'objetivo' 'no es mi objetivo' 'objetivo'
  'objetivo']
 ['objetivo' 'objetivo' 'objetivo' 'objetivo' 'no es mi objetivo']]

Array multiplicado por 10:
[[ 40 460  90  20 200]
 [120 250 100  40 430]
 [140 380 210 440 440]
 [ 30 460 330  60 250]]


In [10]:
"""
2. Crea un nuevo *array* de dos dimensiones con la misma forma que el anterior y con el método que prefieras y realiza lo siguiente:

    - Suma el primer array con el segundo.


    - Aplicar la potencia para el primer array elevado al segundo.
"""

# Crear un nuevo array bidimensional con la misma forma
nuevo_array = np.random.randint(0, 51, size=(4, 5))
print("Nuevo array:\n", nuevo_array)

print("-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-")

# mostrar el primer array
print("Primer array:\n", array)

print("-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-")

# Sumar el primer array con el segundo
suma_arrays = array + nuevo_array
print("Suma de los arrays:\n", suma_arrays)

print("-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-")

# Aplicar la potencia del primer array elevado al segundo
potencia_arrays = np.power(array, nuevo_array)
print("Potencia del primer array elevado al segundo:\n", potencia_arrays)

Nuevo array:
 [[ 9 30 34 38 17]
 [17  2 19 20  5]
 [27 26 24 31 18]
 [10  8 30 44 41]]
-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-
Primer array:
 [[ 4 46  9  2 20]
 [12 25 10  4 43]
 [14 38 21 44 44]
 [ 3 46 33  6 25]]
-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-
Suma de los arrays:
 [[13 76 43 40 37]
 [29 27 29 24 48]
 [41 64 45 75 62]
 [13 54 63 50 66]]
-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-
Potencia del primer array elevado al segundo:
 [[     262144  1073741824  1897516369           0           0]
 [          0         625 -1981284352           0   147008443]
 [-1207959552   603979776  1547765025           0           0]
 [      59049 -1295105792  -859516991           0  -656920359]]


Hay valores en cero por desbordamiento del tipo de elemento, en este caso son valores del tipo int32.