1.4 EJERCICIO MODULO 3 FUNCIONES

# Ejercicios


1. En este ejercicio vamos a tratar de usar algunos de los métodos aprendidos. 

    - Crea un *array*, puede ser bidimensional! Eso si, los valores tienen que estar entre 0-100

    - Calcula: 

        - La media de los elementos
        - La media de las columnas y redondéalo a dos decimales
        - El valor máximo de cada fila
        - El valor mínimo de cada fila
        - Hay algun valor que sea mayor que 90 en tu *array* 
        - Donde los podemos encontrar, cuáles son sus índices
        - Ordena el *array* de mayor a menor

    📝 **NOTA** En este ejercicio os hemos pedido algunos de los métodos, pero sentiros libres de practicar otros para ir asentando los conocimientos. 

In [3]:
#IMPORTANDO LIBRERIAS NECESARIAS
import numpy as np

In [6]:
"""
    1. En este ejercicio vamos a tratar de usar algunos de los métodos aprendidos. 

    - Crea un *array*, puede ser bidimensional! Eso si, los valores tienen que estar entre 0-100

    - Calcula: 

        - La media de los elementos
        - La media de las columnas y redondéalo a dos decimales
        - El valor máximo de cada fila
        - El valor mínimo de cada fila
        - Hay algun valor que sea mayor que 90 en tu *array* 
        - Donde los podemos encontrar, cuáles son sus índices
        - Ordena el *array* de mayor a menor
"""

# Crear un array bidimensional de 5x5 con valores aleatorios entre 0 y 100
array = np.random.randint(0, 101, size=(5, 5))

print("Array original:")
print(array)
print()
print("-----------------------------------------------")
# Calcular la media de todos los elementos del array
media_total = np.mean(array)
print("Media de todos los elementos:", media_total)

print("-----------------------------------------------")
# Calcular la media de cada columna y redondear a dos decimales
media_columnas = np.round(np.mean(array, axis=0), 2)
print("Media de cada columna:")
print(media_columnas)

print("-----------------------------------------------")
# Calcular el valor máximo de cada fila
maximos_filas = np.max(array, axis=1)
print("Valor máximo de cada fila:")
print(maximos_filas)

print("-----------------------------------------------")
# Calcular el valor mínimo de cada fila
minimos_filas = np.min(array, axis=1)
print("Valor mínimo de cada fila:")
print(minimos_filas)

print("-----------------------------------------------")
# Verificar si hay algún valor mayor que 90 en el array
hay_mayor_90 = np.any(array > 90)
print("¿Hay algún valor mayor que 90 en el array?", hay_mayor_90)

# Encontrar los índices de los valores mayores que 90
if hay_mayor_90:
    indices_mayor_90 = np.where(array > 90)
    print("Índices de los valores mayores que 90:")
    print(indices_mayor_90)

print("-----------------------------------------------")
# Ordenar el array de mayor a menor
array_ordenado = np.sort(array.flatten())[::-1]
print("Array ordenado de mayor a menor:")
print(array_ordenado)

print("-----------------------------------------------")


Array original:
[[ 14  37 100  35  28]
 [  8  83  80  18  11]
 [ 65  94  59  73  49]
 [ 75  15   1  11  84]
 [ 83  52  11   9  18]]

-----------------------------------------------
Media de todos los elementos: 44.52
-----------------------------------------------
Media de cada columna:
[49.  56.2 50.2 29.2 38. ]
-----------------------------------------------
Valor máximo de cada fila:
[100  83  94  84  83]
-----------------------------------------------
Valor mínimo de cada fila:
[14  8 49  1  9]
-----------------------------------------------
¿Hay algún valor mayor que 90 en el array? True
Índices de los valores mayores que 90:
(array([0, 2], dtype=int64), array([2, 1], dtype=int64))
-----------------------------------------------
Array ordenado de mayor a menor:
[100  94  84  83  83  80  75  73  65  59  52  49  37  35  28  18  18  15
  14  11  11  11   9   8   1]
-----------------------------------------------
