 # Numpy

 - array:
    - conjunto de datos, nos recuerda a una lista
    - nos permite 1 tipo de dato: int, float, str, bool
    - puede tener n dimensiones -> 1 dimensión podría ser una columna de nuestro df y 2 dimensiones una tabla

- características -> no llevan paréntesis
    - .ndim -> núm de dimensiones
    - .shape -> nos devuelve la forma del array
    - .size -> tamaño del array
    - .dtype -> tipo de dato del array

- creación de arrays:
    - np.array() -> le podemos pasar una lista, lista de listas,...
    - np.arange() -> array de núms consecutivos y una dimensión
    - np.empty() ->
    - np.zeros() ->
    - np.ones() -> 
    - np.random.randint -> 
    - np.random.rand ->
    - np.random.random_sample ->

- Indexación:
    - array 1d -> igual que en una lista [start:stop:step]
    - array 2d -> [star_fila:stop_fila_:step_fila, star_col:stop_col:step_col]

- Operaciones:
    - 

- Filtrado:
    - 


In [1]:
import numpy as np

In [7]:
array = np.array([[1,2,3],[4,5, 6]])

array

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
array.ndim

2

In [9]:
array.shape

(2, 3)

In [10]:
array_3d = np.random.randint(1, 10, (2,3,5))

array_3d

array([[[3, 1, 5, 8, 2],
        [3, 8, 7, 7, 7],
        [9, 4, 6, 6, 4]],

       [[1, 2, 8, 8, 8],
        [2, 9, 7, 3, 1],
        [1, 6, 1, 8, 8]]])

In [11]:
array_3d.shape

(2, 3, 5)

In [12]:
array_1d = np.random.randint(1, 10, 6)

array_1d

array([6, 2, 8, 8, 7, 3])

In [13]:
array_1d.shape

(6,)

In [14]:
array_1d.size

6

In [18]:
array_3d[0, 1, 3]

7

In [19]:
array_4d = np.random.randint(1, 10, (4,2,3,5))

array_4d

array([[[[7, 2, 4, 6, 5],
         [7, 4, 8, 5, 4],
         [5, 6, 7, 4, 6]],

        [[4, 4, 8, 4, 5],
         [1, 3, 9, 9, 3],
         [2, 5, 3, 2, 2]]],


       [[[5, 8, 8, 1, 3],
         [7, 9, 3, 2, 7],
         [6, 6, 3, 9, 9]],

        [[1, 2, 4, 9, 7],
         [1, 4, 7, 5, 4],
         [4, 3, 4, 4, 5]]],


       [[[9, 1, 9, 9, 7],
         [9, 3, 6, 9, 1],
         [7, 8, 2, 9, 9]],

        [[8, 4, 6, 4, 8],
         [4, 1, 1, 5, 6],
         [9, 5, 6, 1, 3]]],


       [[[1, 8, 1, 7, 8],
         [4, 2, 1, 7, 9],
         [2, 8, 1, 8, 1]],

        [[2, 9, 2, 1, 1],
         [4, 9, 2, 1, 7],
         [6, 9, 6, 2, 3]]]])

In [21]:
array_4d[0, 1]

array([[4, 4, 8, 4, 5],
       [1, 3, 9, 9, 3],
       [2, 5, 3, 2, 2]])

In [22]:
lista = [1,2,3,4,5,6]

np.array(lista)

array([1, 2, 3, 4, 5, 6])

In [27]:
np.arange(8).reshape(2,4)

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [30]:
np.empty((2,7, 5), dtype="str")

array([[['', '', '', '', ''],
        ['', '', '', '', ''],
        ['', '', '', '', ''],
        ['', '', '', '', ''],
        ['', '', '', '', ''],
        ['', '', '', '', ''],
        ['', '', '', '', '']],

       [['', '', '', '', ''],
        ['', '', '', '', ''],
        ['', '', '', '', ''],
        ['', '', '', '', ''],
        ['', '', '', '', ''],
        ['', '', '', '', ''],
        ['', '', '', '', '']]], dtype='<U1')

In [31]:
np.random.rand(2,4)

array([[0.25691729, 0.04604603, 0.05595472, 0.21857739],
       [0.80532533, 0.96519634, 0.57806446, 0.9970577 ]])

In [33]:
np.random.random_sample((2,4))

array([[0.74223362, 0.76033112, 0.19317297, 0.20121162],
       [0.59547744, 0.04719603, 0.3640671 , 0.31165908]])

In [34]:
np.random.random_sample()

0.46710934432928675

In [36]:
array_1d

array([6, 2, 8, 8, 7, 3])

In [37]:
array_1d[2]

8

In [40]:
array_2d = np.random.randint(1, 10, (4,5))

array_2d

array([[9, 7, 3, 9, 2],
       [5, 5, 4, 5, 1],
       [2, 3, 1, 2, 7],
       [9, 2, 1, 9, 4]])

In [42]:
array_2d[0:3, ::2]

array([[9, 3, 2],
       [5, 4, 1],
       [2, 1, 7]])

In [ ]:
array_2d[0:3][::2]

In [43]:
array_2d + 100

array([[109, 107, 103, 109, 102],
       [105, 105, 104, 105, 101],
       [102, 103, 101, 102, 107],
       [109, 102, 101, 109, 104]])

In [44]:
array_2d2 = np.random.randint(1, 10, (4,5))

array_2d2

array([[7, 7, 4, 4, 8],
       [7, 7, 6, 3, 3],
       [7, 6, 3, 7, 6],
       [9, 4, 8, 2, 1]])

In [45]:
array_2d2 * array_2d

array([[63, 49, 12, 36, 16],
       [35, 35, 24, 15,  3],
       [14, 18,  3, 14, 42],
       [81,  8,  8, 18,  4]])

In [46]:
array_2d

array([[9, 7, 3, 9, 2],
       [5, 5, 4, 5, 1],
       [2, 3, 1, 2, 7],
       [9, 2, 1, 9, 4]])

In [48]:
masc = array_2d > 5

masc

array([[ True,  True, False,  True, False],
       [False, False, False, False, False],
       [False, False, False, False,  True],
       [ True, False, False,  True, False]])

In [49]:
array_2d[masc]

array([9, 7, 9, 7, 9, 9])

In [50]:
array_2d[array_2d > 5]

array([9, 7, 9, 7, 9, 9])

In [51]:
np.where(array_2d > 5)

(array([0, 0, 0, 2, 3, 3], dtype=int64),
 array([0, 1, 3, 4, 0, 3], dtype=int64))

In [54]:
array_2d > 5

array([[ True,  True, False,  True, False],
       [False, False, False, False, False],
       [False, False, False, False,  True],
       [ True, False, False,  True, False]])

In [52]:
np.where(array_2d > 5, "a", "b")

array([['a', 'a', 'b', 'a', 'b'],
       ['b', 'b', 'b', 'b', 'b'],
       ['b', 'b', 'b', 'b', 'a'],
       ['a', 'b', 'b', 'a', 'b']], dtype='<U1')

In [ ]:
if num > 5:
    print("a")
else:
    if num > 3:
        "b"
    else:
        print("c")

In [56]:
np.where(array_2d > 5, array_2d, 10000)

array([[    9,     7, 10000,     9, 10000],
       [10000, 10000, 10000, 10000, 10000],
       [10000, 10000, 10000, 10000,     7],
       [    9, 10000, 10000,     9, 10000]])

In [ ]:
np.where(array_2d > 5, "a", 
         np.where(array_2d > 3, "b",
                   "c"))

array([['a', 'a', 'c', 'a', 'c'],
       ['b', 'b', 'b', 'b', 'c'],
       ['c', 'c', 'c', 'c', 'a'],
       ['a', 'c', 'c', 'a', 'b']], dtype='<U1')