## Pair Numpy

### Creación y Indexación:

1- Crea un array 1D con 50 valores aleatorio del 10 al 99. Accede a los elementos en las posiciones múltiplos de 5.

2- Crea un array 1D con 30 valores del 1 al 20 (ambos incluidos). Utiliza indexación para obtener los elementos en las posiciones impares.

3- Crea un array 2D de forma (4, 6) con números aleatorios decimales (no deben estar comprendidos solo entre 0 y 1). Accede a la última fila de la matriz. Los decimales deben estar redondeados a 2 decimales.

4- **BONUS:** Crea un array 3D de forma (2, 3, 5) y 50 elementos con números enteros entre 0 y 100 (ambos incluidos). Reemplaza los elementos en posiciones múltiplos de 3 por 0.

### Reshape y Transpose:

*   Ejercicios con reshape:

1-  Crea un array 3D de forma (2, 3, 4) con valores aleatorios entre 1 y 100 (ambos inclusive). Utiliza reshape para convertirlo en un array 2D. Deberás pensar en la forma que es correcta para hacer este cambio.

2-  Crea un array 3D de forma (3, 4, 5) con valores enteros del 1 al 60 (sin incluir). Utiliza reshape para convertirlo en un array 2D.

*   Ejercicios con transpose:

3-  Utiliza el array 3D del ejercicio 2 de reshape. Utiliza transpose para permutar los ejes y obtener un nuevo array con forma (5, 4, 3).

4-  Utiliza el array 3D del ejercicio 3 de reshape. Utiliza transpose para cambiar el orden de los ejes y obtener un nuevo array con forma (3, 5, 4).

### Preguntas teóricas:

*   ¿Qué diferencia existe entre el reshape y el transpose?

*   ¿Y entre el transpose y el swapaxes?

### Funciones Aritméticas y Estadísticas:

1-  Crea un array de tres 3D con elementos entre el 0 y 1 de forma (2, 3, 5) cuyos valores solo tengan 1 decimal.

2-  Crea un array vacío con la misma forma y dimensiones que el array creado anteriormente. Vamos a reemplazar los valores de la matriz vacía que nos acabamos de crear pero basándonos en los valores del primer array bajo las siguientes condiciones:

*   Si el valor del array es igual que la media, se reemplaza por "A".

*   Si el valor del array es mayor que la media, se reemplaza por "B".

*   Si el valor del array es menor que la media, se reemplaza por "C".

*   Si el valor es igual que el máximo, se reemplaza por "D".

*   Si el valor es igual que el mínimo, se reemplaza por "E".

In [12]:
# primero importamos las librerias
import numpy as np

In [13]:
# 1- Crea un array 1D con 50 valores aleatorio del 10 al 99. Accede a los elementos en las posiciones múltiplos de 5.

# Crear un array 1D con 50 valores aleatorios del 10 al 99
array1 = np.random.randint(10, 100, 50)
print("Array original:")
print(array1)

# Acceder a los elementos en las posiciones múltiplos de 5
result1 = array1[::5]
print("\nElementos en posiciones múltiplos de 5:")
print(result1)

Array original:
[76 36 56 75 44 11 14 53 14 18 20 73 90 52 98 97 69 97 34 87 75 61 59 33
 28 77 68 98 66 15 16 20 83 99 58 45 37 16 35 60 41 57 73 85 77 76 44 83
 65 26]

Elementos en posiciones múltiplos de 5:
[76 11 20 97 75 77 16 45 41 76]


In [14]:
# 2- Crea un array 1D con 30 valores del 1 al 20 (ambos incluidos). Utiliza indexación para obtener los elementos en las posiciones impares.

# Crear un array 1D con 30 valores del 1 al 20 (ambos incluidos)
array2 = np.random.randint(1, 21, 30)
print("Array original:")
print(array2)

# Obtener los elementos en las posiciones impares
result2 = array2[1::2]
print("\nElementos en posiciones impares:")
print(result2)

Array original:
[ 8  5  2 11  5  8 10  1 20 17  9 15 16 14 15  9  2 10 14  5 20 19  7 13
  6  1  2 14  7  4]

Elementos en posiciones impares:
[ 5 11  8  1 17 15 14  9 10  5 19 13  1 14  4]


In [15]:
#3- Crea un array 2D de forma (4, 6) con números aleatorios decimales (no deben estar comprendidos solo entre 0 y 1).
# Accede a la última fila de la matriz. Los decimales deben estar redondeados a 2 decimales.

# Crear un array 2D de forma (4, 6) con números aleatorios decimales en un rango específico
array3 = (np.random.random((4, 6)) * 90) + 10  # Escalar y desplazar para obtener el rango entre 10 y 100
array3 = np.round(array3, 2)  # Redondear los decimales a 2 decimales
print("Array 2D original:")
print(array3)

# Acceder a la última fila de la matriz
last_row = array3[-1, :]
print("\nÚltima fila de la matriz:")
print(last_row)

Array 2D original:
[[41.13 28.63 21.94 79.59 12.6  75.47]
 [83.63 56.19 56.   30.9  34.51 38.06]
 [87.3  98.08 43.65 69.51 80.51 28.78]
 [75.42 54.12 99.12 87.42 51.84 94.13]]

Última fila de la matriz:
[75.42 54.12 99.12 87.42 51.84 94.13]


In [16]:
#4- **BONUS:** Crea un array 3D de forma (2, 3, 5) y 50 elementos con números enteros entre 0 y 100 (ambos incluidos). Reemplaza los elementos en posiciones múltiplos de 3 por 0.

# Crear un array 3D de forma (2, 3, 5) con números enteros entre 0 y 100 (ambos incluidos)
array4 = np.random.randint(0, 101, (2, 3, 5))
print("Array 3D original:")
print(array4)

# Reemplazar los elementos en posiciones múltiplos de 3 por 0
array4_flat = array4.flatten()  # Convertir el array a 1D para facilitar el acceso
array4_flat[::3] = 0
array4 = array4_flat.reshape((2, 3, 5))  # Reconstruir el array 3D
print("\nArray 3D con elementos en posiciones múltiplos de 3 reemplazados por 0:")
print(array4)

Array 3D original:
[[[87 10 35 10 40]
  [ 5  1  4 65 15]
  [14 86 49 55  2]]

 [[93 46 29 70 32]
  [43 19 71  7 31]
  [46 98 15 74 13]]]

Array 3D con elementos en posiciones múltiplos de 3 reemplazados por 0:
[[[ 0 10 35  0 40]
  [ 5  0  4 65  0]
  [14 86  0 55  2]]

 [[ 0 46 29  0 32]
  [43  0 71  7  0]
  [46 98  0 74 13]]]


In [17]:
# 1-  Crea un array 3D de forma (2, 3, 4) con valores aleatorios entre 1 y 100 (ambos inclusive). 
# Utiliza reshape para convertirlo en un array 2D. Deberás pensar en la forma que es correcta para hacer este cambio.

# Crear un array 3D de forma (2, 3, 4) con valores aleatorios entre 1 y 100
array_3d = np.random.randint(1, 101, (2, 3, 4))
print("Array 3D original:")
print(array_3d)

# Convertir el array 3D en un array 2D utilizando reshape
array_2d = array_3d.reshape(6, 4)  # 6 filas y 4 columnas para mantener los 24 elementos
print("\nArray 2D resultante:")
print(array_2d)

Array 3D original:
[[[69 72 28 91]
  [69 12 38 26]
  [97 30 55 11]]

 [[15 60 27 94]
  [54 46 50 26]
  [99 27 53 35]]]

Array 2D resultante:
[[69 72 28 91]
 [69 12 38 26]
 [97 30 55 11]
 [15 60 27 94]
 [54 46 50 26]
 [99 27 53 35]]


In [18]:
# 2-  Crea un array 3D de forma (3, 4, 5) con valores enteros del 1 al 61 (sin incluir). Utiliza reshape para convertirlo en un array 2D.

# Crear un array 3D de forma (3, 4, 5) con valores enteros del 1 al 61
array_3d = np.arange(1, 61).reshape(3, 4, 5)
print("Array 3D original:")
print(array_3d)

# Convertir el array 3D en un array 2D utilizando reshape
array_2d = array_3d.reshape(12, 5)  # 12 filas y 5 columnas para mantener los 60 elementos
print("\nArray 2D resultante:")
print(array_2d)

Array 3D original:
[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]
  [16 17 18 19 20]]

 [[21 22 23 24 25]
  [26 27 28 29 30]
  [31 32 33 34 35]
  [36 37 38 39 40]]

 [[41 42 43 44 45]
  [46 47 48 49 50]
  [51 52 53 54 55]
  [56 57 58 59 60]]]

Array 2D resultante:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]
 [36 37 38 39 40]
 [41 42 43 44 45]
 [46 47 48 49 50]
 [51 52 53 54 55]
 [56 57 58 59 60]]


In [21]:
# 3-  Utiliza el array 3D del ejercicio 2 de reshape. Utiliza transpose para permutar los ejes y obtener un nuevo array con forma (5, 4, 3).


# Utilizar transpose para permutar los ejes y obtener un nuevo array con forma (5, 4, 3)
array_transposed = array_3d.transpose(2, 1, 0)  # Cambiar los ejes de (3, 4, 5) a (5, 4, 3)
print("\nArray transpuesto con forma (5, 4, 3):")
print(array_transposed)


Array transpuesto con forma (2, 1, 0):
[[[ 1 21 41]
  [ 6 26 46]
  [11 31 51]
  [16 36 56]]

 [[ 2 22 42]
  [ 7 27 47]
  [12 32 52]
  [17 37 57]]

 [[ 3 23 43]
  [ 8 28 48]
  [13 33 53]
  [18 38 58]]

 [[ 4 24 44]
  [ 9 29 49]
  [14 34 54]
  [19 39 59]]

 [[ 5 25 45]
  [10 30 50]
  [15 35 55]
  [20 40 60]]]


In [26]:
# 4-  Utiliza el array 3D del ejercicio 3 de reshape. Utiliza transpose para cambiar el orden de los ejes y obtener un nuevo array con forma (3, 2, 4).

# Crear un array 3D de forma (3, 4, 5) con valores enteros del 1 al 60 (sin incluir)
array_3d = np.arange(1, 61).reshape(3, 4, 5)
print("Array 3D original:")
print(array_3d)

print("-*-*-*-*-*-*-*-*-*-")

# Utilizar transpose para cambiar el orden de los ejes y obtener un nuevo array con forma (3, 5, 4)
array_transposed = array_3d.transpose(0, 2, 1)  # Cambiar los ejes de (3, 4, 5) a (3, 5, 4)
print("Nuevo Array 3D:")
print(array_transposed)
print("Nueva forma:", array_transposed.shape)

Array 3D original:
[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]
  [16 17 18 19 20]]

 [[21 22 23 24 25]
  [26 27 28 29 30]
  [31 32 33 34 35]
  [36 37 38 39 40]]

 [[41 42 43 44 45]
  [46 47 48 49 50]
  [51 52 53 54 55]
  [56 57 58 59 60]]]
-*-*-*-*-*-*-*-*-*-
Nuevo Array 3D:
[[[ 1  6 11 16]
  [ 2  7 12 17]
  [ 3  8 13 18]
  [ 4  9 14 19]
  [ 5 10 15 20]]

 [[21 26 31 36]
  [22 27 32 37]
  [23 28 33 38]
  [24 29 34 39]
  [25 30 35 40]]

 [[41 46 51 56]
  [42 47 52 57]
  [43 48 53 58]
  [44 49 54 59]
  [45 50 55 60]]]
Nueva forma: (3, 5, 4)


### Preguntas teóricas:

*   ¿Qué diferencia existe entre el reshape y el transpose?

reshape:

Propósito: Cambia la forma del array sin alterar los datos subyacentes.
Uso: Especificas la nueva forma que quieres para el array, siempre que el número total de elementos se mantenga constante.
Ejemplo simple: Cambiar un array de 12 elementos de 1D (una dimensión) a 2D (dos dimensiones) con 3 filas y 4 columnas.

transpose:

Propósito: Permuta los ejes del array.
Uso: Cambia el orden de las dimensiones del array, reorganizando cómo se disponen los elementos.
Ejemplo simple: Convertir un array 2D de 3x4 (3 filas y 4 columnas) a 4x3 (4 filas y 3 columnas) intercambiando filas por columnas.

*   ¿Y entre el transpose y el swapaxes?

transpose:

Propósito: Permuta todos los ejes del array según el orden que especifiques.
Uso: Se utiliza para reordenar completamente las dimensiones del array.
Ejemplo simple: Cambiar un array 3D de forma (2, 3, 4) a (4, 3, 2) especificando el nuevo orden de los ejes.

swapaxes:

Propósito: Intercambia solo dos ejes específicos del array.
Uso: Especificas dos ejes para intercambiar su posición.
Ejemplo simple: Cambiar un array 3D de forma (2, 3, 4) a (4, 3, 2) intercambiando solo el primer y el tercer eje.


In [27]:
""" Funciones Aritméticas y Estadísticas:

1-  Crea un array de tres 3D con elementos entre el 0 y 1 de forma (2, 3, 5) cuyos valores solo tengan 1 decimal.
"""
# Crear el array 3D con valores entre 0 y 1, y redondearlos a 1 decimal
array_3d = np.round(np.random.random((2, 3, 5)), 1)
print("Array 3D original:")
print(array_3d)

Array 3D original:
[[[0.6 0.8 0.5 0.  0.2]
  [0.3 0.6 0.7 0.2 0.4]
  [0.7 0.1 0.6 1.  0.5]]

 [[0.3 0.9 0.7 0.4 0.8]
  [0.5 0.1 0.6 0.3 0.6]
  [0.6 0.5 1.  0.3 0.9]]]


In [32]:
"""
2-  Crea un array vacío con la misma forma y dimensiones que el array creado anteriormente. Vamos a reemplazar los valores de la matriz vacía que nos acabamos de 
crear pero basándonos en los valores del primer array bajo las siguientes condiciones:

*   Si el valor del array es igual que la media, se reemplaza por "A".

*   Si el valor del array es mayor que la media, se reemplaza por "B".

*   Si el valor del array es menor que la media, se reemplaza por "C".

*   Si el valor es igual que el máximo, se reemplaza por "D".

*   Si el valor es igual que el mínimo, se reemplaza por "E".
"""

# Crear un array vacío con la misma forma que array_3d
array_replacement = np.empty(array_3d.shape, dtype=str)


# Calcular la media, el máximo y el mínimo del array original
media = np.mean(array_3d)
maximo = np.max(array_3d)
minimo = np.min(array_3d)

print("la media es:",media) 
print("el maximo es:",maximo)
print("el minimo es:",minimo)


# Usar np.where para reemplazar valores según las condiciones
array_replacement = np.where(array_3d == maximo, 'D',
                    np.where(array_3d == minimo, 'E',
                    np.where(array_3d == media, 'A',
                    np.where(array_3d > media, 'B',
                    np.where(array_3d < media, 'C', '')))))



print("*-*-*-*-*-*-*-*-*-*-*-*")
print("el nuevo array es:",array_replacement)

la media es: 0.5233333333333333
el maximo es: 1.0
el minimo es: 0.0
*-*-*-*-*-*-*-*-*-*-*-*
el nuevo array es: [[['B' 'B' 'C' 'E' 'C']
  ['C' 'B' 'B' 'C' 'C']
  ['B' 'C' 'B' 'D' 'C']]

 [['C' 'B' 'B' 'C' 'B']
  ['C' 'C' 'B' 'C' 'B']
  ['B' 'C' 'D' 'C' 'B']]]
